"""The Numba kernel in classic mode reproduces the NOAA-OWP SNOW-17 Fortran.

Fixtures were generated by compiling NOAA-OWP snow17 `src/snow19/*.f` with `fixtures/snow17_refdriver.f90`
(gfortran -finit-local-zero) and driving EXSNOW19 with the forcing columns. OWP leaves SNOF at 0, so the
comparison uses snof=0.
"""

import gzip
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from flowcast_pipeline.snow.params import CLASSIC, HruParams
from flowcast_pipeline.snow.snow17 import N_OUT, OUTPUTS, day_number_from_march21, initial_state, snow17_kernel

FIXTURES = Path(__file__).parent / "fixtures"


def _load(name: str):
    with gzip.open(FIXTURES / name, "rt") as f:
        f.readline()
        header = f.readline()
        frame = pd.read_csv(f)
    params = {}
    for tok in header.removeprefix("# params ").split():
        k, v = tok.split("=")
        params[k] = [float(x) for x in v.split(",")] if k == "adc" else float(v)
    return frame, params


def _run_classic(frame: pd.DataFrame, p: dict, idt: int) -> np.ndarray:
    params = CLASSIC.replace(
        scf=p["scf"], mfmax=p["mfmax"], mfmin=p["mfmin"], uadj=p["uadj"], si=p["si"], nmf=p["nmf"], tipm=p["tipm"],
        mbase=p["mbase"], pxtemp=p["pxtemp"], plwhc=p["plwhc"], daygm=p["daygm"], adc=tuple(p["adc"]), snof=0.0,
    )  # fmt: skip
    ta = frame["air_temperature"].to_numpy()[:, None]
    px = frame["precip_mm"].to_numpy()[:, None]
    zeros = np.zeros_like(ta)
    hp = HruParams.build(params, np.array([p["alat"]]), np.array([0.0]))
    out = np.zeros((N_OUT, len(ta), 1), dtype=np.float32)
    times = pd.DatetimeIndex(frame["time"])
    snow17_kernel(
        ta, px, (ta <= params.pxtemp).astype(float), zeros, np.full_like(ta, p["pa"]), zeros, zeros,
        day_number_from_march21(times), idt, hp.values, hp.adc, hp.flags, initial_state(1), out,
    )  # fmt: skip
    return out[:, :, 0]


@pytest.mark.parametrize(("fixture", "idt"), [("snow17_owp_ex1_daily.csv.gz", 24), ("snow17_owp_hourly.csv.gz", 1)])
def test_matches_owp_fortran(fixture, idt):
    frame, p = _load(fixture)
    out = _run_classic(frame, p, idt)
    swe = out[OUTPUTS.index("swe")]
    raim = out[OUTPUTS.index("rain_plus_melt")]
    depth = out[OUTPUTS.index("snow_depth")]
    assert frame["swe"].max() > 100
    np.testing.assert_allclose(swe, frame["swe"], atol=0.05 + 1e-4 * frame["swe"].max())
    np.testing.assert_allclose(raim, frame["rain_plus_melt"], atol=0.02)
    np.testing.assert_allclose(np.cumsum(raim), np.cumsum(frame["rain_plus_melt"]), atol=0.5)
    big = frame["swe"] > 5.0
    np.testing.assert_allclose(depth[big], frame["snow_depth"][big], rtol=0.01, atol=0.005)


def test_day_number_matches_exsnow19():
    t = pd.DatetimeIndex(["2021-03-21", "2021-03-20", "2021-01-01", "2020-03-21", "2020-12-31"])
    np.testing.assert_array_equal(day_number_from_march21(t), [0, 364, 286, 0, 285])
