name: deploy

on:
  push:
    branches:
      - main

jobs:
  cdk_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install docker
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: 'infra'
          cdk_subcommand: 'deploy'
          cdk_stack: 'FlowcastStack'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          RDS_PASS: ${{ secrets.RDS_PASS }}
          RDS_HOST: ${{ secrets.RDS_HOST }}
          NCEI_HOST: ${{ secrets.NCEI_HOST }}
          NCEI_EMAIL: ${{ secrets.NCEI_EMAIL }}
